[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.api"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300

[environments.production]
PORT = "8000"
ENVIRONMENT = "production"
HOST = "0.0.0.0"
PYTHONUNBUFFERED = "1"
# API_KEY = "your-generated-api-key-here" # Set this in Railway dashboard 