[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.api"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3

[environments.production]
PORT = "8000" 