# Railway configuration file
[build]
builder = "nixpacks"
buildCommand = "pip install -e ."

[deploy]
startCommand = "python -m uvicorn app.backend.main:app --host=0.0.0.0 --port=$PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 