# Railway configuration file
[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.api"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 